# Minor Arcana - SWORDS and PENTACLES suits

# Minor Arcana - SWORDS suit (Air element - intellect, communication, conflict)
MINOR_ARCANA_SWORDS = [
    {
        "id": 50,
        "name": "Туз Мечей",
        "name_en": "Ace of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "ace",
        "element": "air",
        "keywords": ["ясность мысли", "правда", "справедливость", "новые идеи"],
        "upright_meaning": "Ментальная ясность, новые идеи, справедливость, истина",
        "reversed_meaning": "Замешательство, жестокость, недостаток ясности, ложь"
    },
    {
        "id": 51,
        "name": "Двойка Мечей",
        "name_en": "Two of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "two",
        "element": "air",
        "keywords": ["трудный выбор", "нерешительность", "баланс", "тупик"],
        "upright_meaning": "Трудный выбор, нерешительность, нужда в дополнительной информации",
        "reversed_meaning": "Путаница, информационная перегрузка, ложный выбор"
    },
    {
        "id": 52,
        "name": "Тройка Мечей",
        "name_en": "Three of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "three",
        "element": "air",
        "keywords": ["разбитое сердце", "горе", "предательство", "эмоциональная боль"],
        "upright_meaning": "Разбитое сердце, эмоциональная боль, горе, предательство",
        "reversed_meaning": "Восстановление после сердечной боли, прощение, эмоциональное исцеление"
    },
    {
        "id": 53,
        "name": "Четверка Мечей",
        "name_en": "Four of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "four",
        "element": "air",
        "keywords": ["отдых", "восстановление", "медитация", "созерцание"],
        "upright_meaning": "Отдых, восстановление, медитация, мирное созерцание",
        "reversed_meaning": "Беспокойство, выгорание, недостаток покоя, стагнация"
    },
    {
        "id": 54,
        "name": "Пятерка Мечей",
        "name_en": "Five of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "five",
        "element": "air",
        "keywords": ["конфликт", "поражение", "выигрыш любой ценой", "самоинтересы"],
        "upright_meaning": "Конфликт, дисгармония, выигрыш любой ценой, поражение",
        "reversed_meaning": "Примирение, извинения, прощение, движение вперед"
    },
    {
        "id": 55,
        "name": "Шестерка Мечей",
        "name_en": "Six of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "six",
        "element": "air",
        "keywords": ["переход", "движение вперед", "путешествие", "выздоровление"],
        "upright_meaning": "Переход к лучшему, спокойная вода после бури, исцеление",
        "reversed_meaning": "Застревание в прошлом, сопротивление переменам, неразрешенные проблемы"
    },
    {
        "id": 56,
        "name": "Семерка Мечей",
        "name_en": "Seven of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "seven",
        "element": "air",
        "keywords": ["обман", "хитрость", "кража", "стратегия"],
        "upright_meaning": "Обман, воровство, хитрость, попытка избежать ответственности",
        "reversed_meaning": "Признание в обмане, возвращение украденного, честность"
    },
    {
        "id": 57,
        "name": "Восьмерка Мечей",
        "name_en": "Eight of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "eight",
        "element": "air",
        "keywords": ["ограничения", "ловушка", "изоляция", "самоограничения"],
        "upright_meaning": "Чувство ловушки, самоограничения, изоляция, негативное мышление",
        "reversed_meaning": "Освобождение, новые перспективы, преодоление ограничений"
    },
    {
        "id": 58,
        "name": "Девятка Мечей",
        "name_en": "Nine of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "nine",
        "element": "air",
        "keywords": ["тревога", "ночные кошмары", "вина", "отчаяние"],
        "upright_meaning": "Глубокая тревога, ночные кошмары, вина, ментальная пытка",
        "reversed_meaning": "Восстановление, надежда, преодоление депрессии, внутренняя турбулентность"
    },
    {
        "id": 59,
        "name": "Десятка Мечей",
        "name_en": "Ten of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "ten",
        "element": "air",
        "keywords": ["болезненный конец", "предательство", "крах", "дно"],
        "upright_meaning": "Болезненный конец, предательство, крах, достижение дна",
        "reversed_meaning": "Восстановление, возрождение, десять сражений закончилось"
    },
    {
        "id": 60,
        "name": "Паж Мечей",
        "name_en": "Page of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "page",
        "element": "air",
        "keywords": ["любопытство", "бдительность", "энергичность", "умственная активность"],
        "upright_meaning": "Любопытный ум, бдительность, энергичная мыслительная активность",
        "reversed_meaning": "Хулиган, сплетни, недостаток дипломатии, безрассудство"
    },
    {
        "id": 61,
        "name": "Рыцарь Мечей",
        "name_en": "Knight of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "knight",
        "element": "air",
        "keywords": ["быстрое действие", "амбиции", "прямота", "импульсивность"],
        "upright_meaning": "Амбициозный, действующий быстро, прямолинейный, храбрый",
        "reversed_meaning": "Безрассудный, агрессивный, недипломатичный, слишком поспешный"
    },
    {
        "id": 62,
        "name": "Королева Мечей",
        "name_en": "Queen of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "queen",
        "element": "air",
        "keywords": ["независимая", "прямая", "принципиальная", "рациональная"],
        "upright_meaning": "Независимая, прямолинейная, принципиальная, справедливая",
        "reversed_meaning": "Злобная, жестокая, холодно-расчетливая, мстительная"
    },
    {
        "id": 63,
        "name": "Король Мечей",
        "name_en": "King of Swords",
        "type": "minor",
        "suit": "swords",
        "value": "king",
        "element": "air",
        "keywords": ["интеллектуальная сила", "справедливость", "правда", "этические принципы"],
        "upright_meaning": "Интеллектуальная сила, справедливость, правда, этическое поведение",
        "reversed_meaning": "Жестокость, абьюз власти, беспощадность, манипулятивность"
    }
]

# Minor Arcana - PENTACLES suit (Earth element - material, money, career, health)
MINOR_ARCANA_PENTACLES = [
    {
        "id": 64,
        "name": "Туз Пентаклей",
        "name_en": "Ace of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "ace",
        "element": "earth",
        "keywords": ["новая возможность", "проявление", "материальная выгода", "процветание"],
        "upright_meaning": "Новая работа или финансовая возможность, материальная выгода, проявление",
        "reversed_meaning": "Упущенная возможность, недостаток планирования, плохие инвестиции"
    },
    {
        "id": 65,
        "name": "Двойка Пентаклей",
        "name_en": "Two of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "two",
        "element": "earth",
        "keywords": ["баланс", "адаптивность", "управление временем", "приоритеты"],
        "upright_meaning": "Множественные приоритеты, управление временем, адаптивность",
        "reversed_meaning": "Дисорганизованность, переутомление, недостаток баланса"
    },
    {
        "id": 66,
        "name": "Тройка Пентаклей",
        "name_en": "Three of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "three",
        "element": "earth",
        "keywords": ["сотрудничество", "командная работа", "мастерство", "строительство"],
        "upright_meaning": "Сотрудничество, командная работа, изучение от других, построение проектов",
        "reversed_meaning": "Недостаток командной работы, некомпетентность, отсутствие сотрудничества"
    },
    {
        "id": 67,
        "name": "Четверка Пентаклей",
        "name_en": "Four of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "four",
        "element": "earth",
        "keywords": ["сбережения", "безопасность", "консерватизм", "скупость"],
        "upright_meaning": "Сбережения, финансовая безопасность, консерватизм в деньгах",
        "reversed_meaning": "Жадность, материальная потеря, финансовая неуверенность"
    },
    {
        "id": 68,
        "name": "Пятерка Пентаклей",
        "name_en": "Five of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "five",
        "element": "earth",
        "keywords": ["финансовые проблемы", "бедность", "нужда", "изоляция"],
        "upright_meaning": "Финансовые проблемы, бедность, ощущение оставленности",
        "reversed_meaning": "Восстановление от финансовых потерь, духовная бедность"
    },
    {
        "id": 69,
        "name": "Шестерка Пентаклей",
        "name_en": "Six of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "six",
        "element": "earth",
        "keywords": ["щедрость", "благотворительность", "взаимность", "справедливость"],
        "upright_meaning": "Щедрость, благотворительность, справедливое распределение богатства",
        "reversed_meaning": "Эгоизм, долги, неравенство в отношениях"
    },
    {
        "id": 70,
        "name": "Семерка Пентаклей",
        "name_en": "Seven of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "seven",
        "element": "earth",
        "keywords": ["долгосрочные инвестиции", "терпение", "настойчивость", "оценка"],
        "upright_meaning": "Долгосрочные инвестиции, терпение, настойчивость, ожидание результатов",
        "reversed_meaning": "Недостаток настойчивости, плохие инвестиции, нетерпение"
    },
    {
        "id": 71,
        "name": "Восьмерка Пентаклей",
        "name_en": "Eight of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "eight",
        "element": "earth",
        "keywords": ["мастерство", "образование", "умение", "упорный труд"],
        "upright_meaning": "Мастерство, изучение новых навыков, упорный труд, детализация",
        "reversed_meaning": "Недостаток фокуса, посредственность, недостаток амбиций"
    },
    {
        "id": 72,
        "name": "Девятка Пентаклей",
        "name_en": "Nine of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "nine",
        "element": "earth",
        "keywords": ["материальное изобилие", "роскошь", "самодостаточность", "процветание"],
        "upright_meaning": "Материальное изобилие, роскошь, самодостаточность, независимость",
        "reversed_meaning": "Переоцененные ценности, финансовые потери, зависимость от других"
    },
    {
        "id": 73,
        "name": "Десятка Пентаклей",
        "name_en": "Ten of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "ten",
        "element": "earth",
        "keywords": ["наследие", "финансовая безопасность", "семейное богатство", "традиции"],
        "upright_meaning": "Наследие, долгосрочная финансовая безопасность, семейное богатство",
        "reversed_meaning": "Финансовые потери, семейные конфликты из-за денег"
    },
    {
        "id": 74,
        "name": "Паж Пентаклей",
        "name_en": "Page of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "page",
        "element": "earth",
        "keywords": ["проявление", "финансовая возможность", "умение", "прагматизм"],
        "upright_meaning": "Новая финансовая возможность, проявление идей, изучение навыков",
        "reversed_meaning": "Недостаток прогресса, плохое планирование, нереализованный потенциал"
    },
    {
        "id": 75,
        "name": "Рыцарь Пентаклей",
        "name_en": "Knight of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "knight",
        "element": "earth",
        "keywords": ["упорный труд", "продуктивность", "рутина", "надежность"],
        "upright_meaning": "Упорный труд, надежность, продуктивность, планомерность",
        "reversed_meaning": "Лень, недостаток амбиций, застой, трудоголизм"
    },
    {
        "id": 76,
        "name": "Королева Пентаклей",
        "name_en": "Queen of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "queen",
        "element": "earth",
        "keywords": ["практичность", "заботливость", "щедрость", "ресурсы"],
        "upright_meaning": "Практичная, заботливая, щедрая, хорошо управляет ресурсами",
        "reversed_meaning": "Эгоизм, жадность, недоверие, финансовая зависимость"
    },
    {
        "id": 77,
        "name": "Король Пентаклей",
        "name_en": "King of Pentacles",
        "type": "minor",
        "suit": "pentacles",
        "value": "king",
        "element": "earth",
        "keywords": ["финансовый успех", "безопасность", "дисциплина", "изобилие"],
        "upright_meaning": "Финансовый успех, безопасность, щедрость, дисциплина",
        "reversed_meaning": "Жадность, материализм, финансовые потери, коррупция"
    }
]